name       : wxwidgets
version    : 3.0.3
release    : 10
source     :
    - https://github.com/wxWidgets/wxWidgets/releases/download/v3.0.3/wxWidgets-3.0.3.tar.bz2 : 08c8033f48ec1b23520f036cde37b5ae925a6a65f137ded665633ca159b9307b
license    : wxWinFDL-3
component  : desktop.library
summary    : Cross-platform UI toolkit library
description: |
    wxWidgets gives you a single, easy-to-use API for writing GUI applications on multiple platforms that still utilize the native platform's controls and utilities. Link with the appropriate library for your platform and compiler, and your application will adopt the look and feel appropriate to that platform. On top of great GUI functionality, wxWidgets gives you: online help, network programming, streams, clipboard and drag and drop, multithreading, image loading and saving in a variety of popular formats, database support, HTML viewing and printing, and much more.
emul32     : yes
patterns   :
    - devel : /usr/bin
builddeps  :
    - pkgconfig32(atk)
    - pkgconfig32(expat)
    - pkgconfig32(freetype2)
    - pkgconfig32(gl)
    - pkgconfig32(glu)
    - pkgconfig32(gnutls)
    - pkgconfig32(gtk+-2.0)
    - pkgconfig32(ice)
    - pkgconfig32(libnotify)
    - pkgconfig32(liblzma)
    - pkgconfig32(libpng)
    - pkgconfig32(libtiff-4)
    - pkgconfig32(sm)
    - pkgconfig32(xxf86vm)
    - pkgconfig32(zlib)
    - libjpeg-turbo-32bit-devel
setup      : |
    %configure --enable-printfposparam --with-gtk=2
build      : |
    %make
install    : |
    %make_install

    # Ensure multilib works for wxwidgets
    rm -v $installdir/usr/bin/wx-config
    install -m 00755 $pkgfiles/wx-config $installdir/usr/bin/wx-config
