name       : wxwidgets
version    : 3.0.5
release    : 27
source     :
    - https://github.com/wxWidgets/wxWidgets/releases/download/v3.0.5/wxWidgets-3.0.5.tar.bz2 : 8aacd56b462f42fb6e33b4d8f5d40be5abc3d3b41348ea968aa515cc8285d813
license    : LGPL-2.0-or-later WITH WxWindows-exception-3.1
component  : desktop.library
summary    : Cross-platform UI toolkit library
description: |
    wxWidgets gives you a single, easy-to-use API for writing GUI applications on multiple platforms that still utilize the native platform's controls and utilities. Link with the appropriate library for your platform and compiler, and your application will adopt the look and feel appropriate to that platform. On top of great GUI functionality, wxWidgets gives you: online help, network programming, streams, clipboard and drag and drop, multithreading, image loading and saving in a variety of popular formats, database support, HTML viewing and printing, and much more.
emul32     : yes
patterns   :
    - 32bit-devel :
        - /usr/share/wxwidgets/wx-config32
    - devel :
        - /usr/bin
        - /usr/share/wxwidgets/wx-config
builddeps  :
    - pkgconfig(gstreamer-plugins-base-1.0)
    - pkgconfig32(atk)
    - pkgconfig32(cairo)
    - pkgconfig32(expat)
    - pkgconfig32(fontconfig)
    - pkgconfig32(freetype2)
    - pkgconfig32(gdk-pixbuf-2.0)
    - pkgconfig32(gio-2.0)
    - pkgconfig32(gl)
    - pkgconfig32(glu)
    - pkgconfig32(gnutls)
    - pkgconfig32(gtk+-2.0)
    - pkgconfig32(ice)
    - pkgconfig32(liblzma)
    - pkgconfig32(libnotify)
    - pkgconfig32(libpng)
    - pkgconfig32(libtiff-4)
    - pkgconfig32(libturbojpeg)
    - pkgconfig32(pangocairo)
    - pkgconfig32(sm)
    - pkgconfig32(x11)
    - pkgconfig32(xcomposite)
    - pkgconfig32(xcursor)
    - pkgconfig32(xdamage)
    - pkgconfig32(xext)
    - pkgconfig32(xfixes)
    - pkgconfig32(xinerama)
    - pkgconfig32(xrandr)
    - pkgconfig32(xrender)
    - pkgconfig32(xxf86vm)
    - pkgconfig32(zlib)
setup      : |
    %patch -p1 < $pkgfiles/Fix-default-enable-mediactrl.patch

    export exOpts=""
    if [ ! -z "${EMUL32BUILD}" ]; then
        exOpts="--disable-gtktest"
    else
        exOpts="--enable-mediactrl"
    fi

    %configure \
        --disable-precomp-headers \
        --enable-printfposparam \
        --with-gtk \
        $exOpts
build      : |
    %make
install    : |
    %make_install

    # Ensure wx-config supports multilib.
    install -dm00755 $installdir/usr/share/wxwidgets
    mv $installdir/usr/bin/wx-config $installdir/usr/share/wxwidgets
    if [ ! -z "${EMUL32BUILD}" ]; then
        mv $installdir/usr/share/wxwidgets/wx-config $installdir/usr/share/wxwidgets/wx-config32
    fi
    install -Dm00755 $pkgfiles/wx-config -t $installdir/usr/bin
