name       : wxwidgets
version    : 3.0.2
release    : 4
source     :
    - http://internode.dl.sourceforge.net/project/wxwindows/3.0.2/wxWidgets-3.0.2.tar.bz2 : 346879dc554f3ab8d6da2704f651ecb504a22e9d31c17ef5449b129ed711585d
license    : wxWinFDL-3
summary    : Cross-platform UI toolkit library
description: |
    wxWidgets gives you a single, easy-to-use API for writing GUI applications on multiple platforms that still utilize the native platform's controls and utilities. Link with the appropriate library for your platform and compiler, and your application will adopt the look and feel appropriate to that platform. On top of great GUI functionality, wxWidgets gives you: online help, network programming, streams, clipboard and drag and drop, multithreading, image loading and saving in a variety of popular formats, database support, HTML viewing and printing, and much more.
patterns   :
    - devel: /usr/bin
builddeps  :
    - pkgconfig(gtk+-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(sm)
    - pkgconfig(ice)
    - pkgconfig(gl)
    - pkgconfig(glu)
    - pkgconfig(libnotify)
    - pkgconfig(gnutls)
    - libjpeg-turbo-devel
setup      : |
    %configure --enable-printfposparam
build      : |
    %make
install    : |
    %make_install
